### ISSUE TITLE
Filled Contour Polygons could fail for certain data value maximum

### ISSUE THREAD

**Issue by bebbit** [ccrook/QGIS-Contour-Plugin#41] opened 2020-06-30 10:03 UTC
When calling the contour plugin from the qgis toolbox there are issues trying to create filled polygons for certain attributes in a shapefile. The created Output will have holes where no class/polygon is created.
![grafik](https://user-images.githubusercontent.com/67594322/86105424-99330900-babf-11ea-8312-6c56e4acab45.png)

Certain classes couldn't be generated and the log shows that Features could not get written to the output.
![grafik](https://user-images.githubusercontent.com/67594322/86099885-5f123900-bab8-11ea-9729-9d0e7cd48871.png)

It happens no matter how many classes are chosen or what method for the contour level calculation is chosen. Also it has no effect to change whether contours are extended up or below max and min.

It might also not be related to amount of points since it does work for certain attributes while it does not work for others in the same shapefile. It also does not matter if the attributes data type is real or integer.

It does work though if instead of **filled contour polygons** only **contour lines** are created.

If the creation fails as mentioned above the workaround is to set the _MaxContourValue_ by hand. If you do set the value to the data maximum it still fails, but if you set it slightly above or below the data maximum then all classes are generated (of course classes are then slightly off maximum as well).

My test data set has a data maximum of 6.5 which made the algorithm to fail when _MinimumContourValue_ and _MaximumContourValue_ are omitted so that min and max are calculated from the attribute. When manually set MaxContourValue to 6.5 it also fails (it also fails for 6.7/6.9). Setting _MaxContourValue_ to 6.4/6.6/6.8 or 6.500001 made the algorithm to work as expected.
Interestingly, directly changing the data value of one of the data points to a specific value (that works if chosen for _MaxContourValue_ for example 6.6) does seem to work without the need to adjust _MaxContourValue_ manually to be slighty off the data maximum.
However, changing one former maximum data point value from 6.5 to 6.6 makes the algorithm to work but changing a lot of the points to 6.6 made the algorithm to fail again. I suspect that not one value leads to problems here but the mixture of values and that it might be related to some problems during classification or min/max/range calculation maybe due to some rounding or trimming of values.

Since I'm not able to investigate further into the plugins code I can only provide my test data set

I've tested on two different Win10 machines with QGIS 3.6.2-Noosa, 3.10.2-A Coruña and 3.10.3-A Coruña with the recent version of the plugin.
[test_data_set.zip](https://github.com/ccrook/QGIS-Contour-Plugin/files/4850986/test_data_set.zip)

**Comment by ccrook** [comment] 2020-06-30 19:16
Hi @bebbit Thanks for you very detailed reporting and for providing the test data set.  The issue is not new, and comes from the matplotlib library that the contour module is using to generated the contours, which in some circumstances can lead to invalid polygons being constructed where the polygons intersect the boundary of the countour data set.  This generally happens when it is using a triangulation to do contouring - generally it tries to use the data as a grid by choice is the issue doesn't usually happen with gridded data.  I'll have a look at this data set to see if it sheds any more light on the issue, or on a work around.

**Comment by ccrook** [comment] 2022-11-16 21:33
Duplicate of #38

**Closed by ccrook** 2022-11-16 21:33 UTC
