### ISSUE TITLE
Blank polygon generated 

### ISSUE THREAD

**Issue by idealist33** [ccrook/QGIS-Contour-Plugin#40] opened 2020-06-09 14:57 UTC
Hello, I made a filled contour polygons with user selected contour levels, but there are some blank polygons...
can you tell me how to resolve it?

===========Here is a log ==============
`QGIS 버전: 3.12.3-București
QGIS 코드 리비전: 8234261527
Qt 버전: 5.11.2
GDAL 버전: 3.0.4
GEOS 버전: 3.8.1-CAPI-1.13.3
PROJ 버전: Rel. 6.3.2, May 1st, 2020
알고리즘 처리 중...
'Generate Contours' 알고리즘 시작…
입력 파라미터:
{ 'ContourInterval' : 0, 'ContourLevels' : '0.1 0.7 1.4 2.2 2.9 3.6 5.4 7.2 9.0 11 13 14 16 18 20 22 23 25 29 32 36 54 72 90 108 126 144 162 180 198 216', 'ContourMethod' : 4, 'ContourType' : 1, 'DuplicatePointTolerance' : None, 'ExtendOption' : 0, 'InputField' : '\"VAL_KM\"', 'InputLayer' : 'C:\\Users\\peter\\Documents\\testshape.shp|layername=testshape', 'LabelDecimalPlaces' : 1, 'LabelTrimZeros' : False, 'LabelUnits' : 'kmh', 'MaxContourValue' : 216, 'MinContourValue' : 0.1, 'NContour' : 500, 'OutputLayer' : 'TEMPORARY_OUTPUT' }

Triangulating 701 points
Contouring 1392 triangles
객체를 Output_layer_9ba0b41c_c170_416b_9de5_a87117ba7c18에 쓸 수 없습니다
객체를 Output_layer_9ba0b41c_c170_416b_9de5_a87117ba7c18에 쓸 수 없습니다
0.35 초만에 실행을 완료했습니다
결과:
{'OutputLayer': 'Output_layer_9ba0b41c_c170_416b_9de5_a87117ba7c18'}

출력 레이어 불러오기
'Generate Contours' 알고리즘을 처리했습니다`

[response_wind_.zip](https://github.com/ccrook/QGIS-Contour-Plugin/files/4752867/response_wind_.zip)
![qgis](https://user-images.githubusercontent.com/10533766/84163904-ef0e2580-aaac-11ea-821b-f7a7fff6b459.PNG)

**Comment by ccrook** [comment] 2022-11-16 21:34
Duplicate of #38

**Closed by ccrook** 2022-11-16 21:34 UTC
